import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useSession, signIn, signOut } from "next-auth/react"

export default function Home() {

  const { data:session }  = useSession()
        
  return(
    

    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      { session?
    <>
      Signed in as {session.user.email} <br />
      <button onClick={() => signOut()}>Sign out</button>
    </>:<>
    Not signed in acab<br />
    <button onClick={() => signIn()}>Sign in</button>
    </>
  }
      
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome {session?session.user.email:``}
        </h1>
      
        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        
      </main>

      <footer className={styles.footer}>
       
      </footer>
    </div>
  )
}
