import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Menu from '../components/Menu'
import { useSession, signIn, signOut } from "next-auth/react"

export default function Home() {

  const { data:session }  = useSession()
  console.log(session?session.user.email:``)
        
  return(
        <div className={styles.container}>
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Menu />
      
          <main className={styles.main}>
            <h1 className={styles.title}>
              Welcome <br />
              {session?session.user.email:``} <br/>
              {session?<button onClick={() => signOut()}>Sign out</button>:<button onClick={() => signIn()}>Sign in</button>}
            </h1>
          
            <p className={styles.description}>
              Get started by editing{' '}
              <code className={styles.code}>pages/index.js</code>
            </p>            
          </main>
          <footer className={styles.footer}>          
          </footer>
    </div>
  )
}
